Codeception5support
qase-tms/qase-codeception pull request #8
Opened 2022-09-09 15:14 UTC by in4s

2022-09-15 11:23 UTC, 1ivliev requested changes
https://github.com/qase-tms/qase-php-client-utils

2022-09-15 11:23 UTC, 1ivliev commented on composer.json
>          "qase/php-client-utils": "^1.0.1",
needed update

2022-09-23 11:13 UTC, in4s commented on composer.json
>          "qase/php-client-utils": "^1.0.1",
done

2022-09-29 05:28 UTC, 1ivliev approved these changes

2022-10-27 20:08 UTC, 1ivliev approved these changes

2022-10-27 20:08 UTC, merged